language: cpp
sudo: required
dist: xenial
compiler:
  - gcc
  #- clang
os:
  - linux
install:
addons:
  apt:
    update: true

env:
  - BUILD_TYPE=debug
script:
  # once CMake has done its job we just build using make as usual
  - make VERBOSE=1
