name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
    # Some projects don't allow in-source building, so create a separate build directory
    # We'll use this as our working directory for all subsequent commands
    run:|
      sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
      sudo apt-get update -y
      sudo apt-get install g++-7 -y
      sudo apt install -y gcc-7 gcc-7-multilib g++-7 g++-7-multilib
      sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 100
      which gcc
      gcc --version
      which g++
      g++ --version
      sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 100
      sudo update-alternatives --config gcc
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 100
      sudo update-alternatives --config g++
      which gcc
      gcc --version
      which g++
      g++ --version
      cd ..
      git clone https://github.com/Microsoft/vcpkg.git
      cd vcpkg
      ./bootstrap-vcpkg.sh
      ./vcpkg integrate install
      sudo ln -s /home/travis/build/edidada/vcpkg/vcpkg /usr/bin
      vcpkg search sqlite
      vcpkg install grpc
      vcpkg list
